#!/bin/bash

printf "Content: text/html\n\n"

printf "<!DOCTYPE html>\n"
printf "<html>\n"
printf "\t<head>\n\t\t<title>Variabili d'ambiente</title>\n\t</head>\n"
printf "\t<body>\n"
printf "\t\t<pre>\n"

set

printf "\t\t</pre>"
printf "\n\t</body>\n</html>"
